create table if not exists app_users (
  id bigint generated by default as identity primary key,
  name text not null,
  username text not null unique,
  password text not null,
  created_at timestamptz not null default now()
);

create table if not exists companies (
  id bigint generated by default as identity primary key,
  name text not null,
  street text not null,
  number text not null,
  city text not null,
  state text not null,
  created_at timestamptz not null default now()
);

create table if not exists customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  city text not null,
  state text not null,
  created_at timestamptz not null default now()
);

create table if not exists employees (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  created_at timestamptz not null default now()
);

create table if not exists inventory_items (
  id bigint generated by default as identity primary key,
  description text not null,
  vn text not null,
  value numeric not null default 0,
  plate text not null,
  created_at timestamptz not null default now()
);

create table if not exists inventory_photos (
  id bigint generated by default as identity primary key,
  inventory_id bigint not null references inventory_items(id) on delete cascade,
  image_data text not null,
  created_at timestamptz not null default now()
);

create table if not exists expense_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists production_records (
  id bigint generated by default as identity primary key,
  number bigint generated by default as identity unique,
  group_name text not null,
  ft numeric not null default 0,
  production_date date not null,
  company_id bigint not null references companies(id),
  customer_id bigint not null references customers(id),
  hh_17x30 numeric not null default 0,
  hh_24x36 numeric not null default 0,
  cost_ft numeric not null default 0,
  value_ft numeric not null default 0,
  cost_hh numeric not null default 0,
  value_hh numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists production_expenses (
  id bigint generated by default as identity primary key,
  production_id bigint not null references production_records(id) on delete cascade,
  expense_type_id bigint not null references expense_types(id),
  value numeric not null default 0,
  created_at timestamptz not null default now()
);

insert into app_users (name, username, password)
values ('Admin', 'admin', 'admin')
on conflict (username) do nothing;
